MachineRental/Models/Attachment.cs
using MachineRental.Models.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MachineRental.Models
{
    public class Attachment
    {
        [Display(Name = "Numéro")]
        public int Id { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "dd/MM/yyyy")]
        [Display(Name = "Date du bon")]
        public DateTime AttachmentDate { get; set; } = DateTime.Now;

        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "dd/mm/yyyy")]
        //[Display(Name = "Date de signature")]
        //public DateTime AttachmentSignatureDate { get; set; } = DateTime.Now;

        [Required]
        [Display(Name = "Heures de travail")]
        public long WorkingHoursTicks { get; set; }

        [Display(Name = "Observations")]
        public string Remarks { get; set; }

        [NotMapped]
        [Required]
        [Range(typeof(bool), "true", "true", ErrorMessage = "Merci de cocher ce champs avant soumission du formulaire")]
        [Display(Name = "Valider l'exactitude des informations avant envoi")]
        public bool IsApproved { get; set; }

        [NotMapped]
        [Display(Name = "Ajouter Signature Client", ShortName = "Signature")]
        [Range(typeof(bool), "true", "true", ErrorMessage = "Le champ Signature Client est requis")]
        public bool IsSigned { get; set; }

        [Required]
        [Display(Name = "Signature du responsable de chantier")]
        public int SignatureImgId { get; set; }
        public SignatureImg SignatureImg { get; set; }

        public int RentalId { get; set; }
        public Rental Rental { get; set; }
    }
}

MachineRental/ViewModels/AttachmentViewModel.cs
using MachineRental.Models;
using MachineRental.Models.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MachineRental.ViewModels
{
    public class AttachmentViewModel
    {
        public Attachment Attachment { get; set; }

        public Rental Rental { get; set; }

        public SignatureImg SignatureImg { get; set; }

        public IEnumerable<Customer> Customers { get; set; }

        public int Hours { get; set; }

        public int Minutes { get; set; }

        public string dataUrl { get; set; }
    }
}

MachineRental/Controllers/AttachmentController.cs
using MachineRental.Common;
using MachineRental.Models;
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using MachineRental.ViewModels;
using MachineRental.Models.Common;
using System.Net;
using Microsoft.AspNet.Identity;

namespace MachineRental.Controllers
{
    public class AttachmentController : Controller
    {
        private readonly ApplicationDbContext _context = new ApplicationDbContext();

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }


        // GET: Attachments
        public async Task<ActionResult> Index()
        {
            var viewModel = new List<Attachment>();

            //var userConn = await HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().FindByEmailAsync(User.Identity.Name);

            if (User.IsInRole(Constant.Machinist))
            {
                var temp1 = await _context.Machinist.Where(m => m.Email == User.Identity.Name).Select(m => m.Id).FirstOrDefaultAsync();

                viewModel = _context.Attachment
                                .Include(s => s.SignatureImg)
                                .Include(r => r.Rental)
                                .Include(m => m.Rental.Machinist)
                                .Include(m => m.Rental.Machine)
                                .Include(a => a.Rental.Address)
                                .Include(c => c.Rental.Order.Customer)
                                .Where(m => m.Rental.MachinistId == temp1)
                                .ToList();

                return View("Attachments", viewModel);
            }


            viewModel = _context.Attachment
                            .Include(s => s.SignatureImg)
                            .Include(r => r.Rental)
                            .Include(m => m.Rental.Machinist)
                            .Include(m => m.Rental.Machine)
                            .Include(a => a.Rental.Address)
                            .Include(c => c.Rental.Order.Customer)
                            .ToList();

            return View("Attachments", viewModel);
        }

        // GET: Attachment/Create
        [HttpGet]
        public ActionResult Create()
        {
            var viewModel = new AttachmentViewModel
            {
                Attachment = new Models.Attachment(),
                SignatureImg = new SignatureImg(),
                Customers = _context.Customer.ToList(),
                Rental = _context.Rental.Single(r => r.Id == 1)
            };

            return View("AttachmentsForm", viewModel);
        }

        // GET: Attachment/Edit/{id}
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var attachment = _context.Attachment
                                .Include(s => s.SignatureImg)
                                .Include(r => r.Rental)
                                .Include(m => m.Rental.Machinist)
                                .Include(m => m.Rental.Machine)
                                .Include(a => a.Rental.Address)
                                .Include(c => c.Rental.Order.Customer)
                                .SingleOrDefault(m => m.Id == id);

            if (attachment == null)
                return HttpNotFound();

            attachment.IsApproved = attachment.IsSigned = true;

            var viewModel = new AttachmentViewModel
            {
                Attachment = attachment,
                SignatureImg = attachment.SignatureImg,
                Rental = attachment.Rental,
                Customers = _context.Customer.ToList(),
                Hours = TimeSpan.FromTicks(attachment.WorkingHoursTicks).Hours,
                Minutes = TimeSpan.FromTicks(attachment.WorkingHoursTicks).Minutes
            };

            return View("AttachmentsForm", viewModel);
        }

        //[Authorize(Roles = Constant.Machinist)]
        [HttpGet]
        public ActionResult Generate(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var rental = _context.Rental
                .Include(a => a.Address)
                .Include(c => c.Order.Customer)
                .Include(m => m.Machinist)
                .Include(m => m.Machine)
                .SingleOrDefault(r => r.Id == id);

            if (rental == null)
                return HttpNotFound();

            var viewModel = new AttachmentViewModel
            {
                Attachment = new Attachment(),
                SignatureImg = new SignatureImg(),
                Rental = rental,
                Customers = _context.Customer.ToList()
            };

            return View("AttachmentsForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]  // Prevent Cross Site Request Forgery (CSRF) Attacks by generating and comparing Token automatically
        public async Task<ActionResult> Save(
        [Bind(Include = "Id, RentalStatus")] Rental rental,
        [Bind(Include = "Id, Data")] SignatureImg SignatureImg,
        [Bind(Include = "Id, AttachmentDate, Remarks, IsApproved, IsSigned")] Attachment attachment,
        string dataUrl, int hours, int minutes)
        {
            if (!ModelState.IsValid)
            {
                // if new attachment
                if (attachment.Id == 0)
                {
                    var viewModel = new AttachmentViewModel
                    {
                        Attachment = attachment,
                        SignatureImg = SignatureImg,
                        Rental = _context.Rental.Include(c => c.Order.Customer)
                                                .Include(c => c.Address)
                                                .Include(c => c.Machinist)
                                                .Include(m => m.Machine)
                                                .Single(r => r.Id == rental.Id),
                        dataUrl = dataUrl,
                        Customers = _context.Customer.ToList(),
                        Hours = hours,
                        Minutes = minutes
                    };
                    return View("AttachmentsForm", viewModel);
                }
                // if update attachment
                else if (attachment.Id != 0)
                {
                    var attachmentDb = _context.Attachment
                                        .Include(s => s.SignatureImg)
                                        .Include(r => r.Rental)
                                        .Include(m => m.Rental.Machinist)
                                        .Include(m => m.Rental.Machine)
                                        .Include(a => a.Rental.Address)
                                        .Include(c => c.Rental.Order.Customer)
                                        .SingleOrDefault(m => m.Id == attachment.Id);

                    var viewModel = new AttachmentViewModel
                    {
                        Attachment = attachmentDb,
                        SignatureImg = attachmentDb.SignatureImg,
                        Rental = attachmentDb.Rental,
                        Customers = _context.Customer.ToList(),
                        Hours = TimeSpan.FromTicks(attachmentDb.WorkingHoursTicks).Hours,
                        Minutes = TimeSpan.FromTicks(attachmentDb.WorkingHoursTicks).Minutes
                    };
                    return View("AttachmentsForm", viewModel);
                }
            }

            // if New attachment
            if (attachment.Id == 0)
            {
                byte[] bytes = Convert.FromBase64String(dataUrl.Split(',')[1]);
                SignatureImg.Data = bytes;
                _context.SignatureImg.Add(SignatureImg);
                _context.SaveChanges();

                attachment.SignatureImgId = SignatureImg.Id;
                attachment.RentalId = rental.Id;

                var workingHours = new TimeSpan(hours, minutes, 0);
                attachment.WorkingHoursTicks = workingHours.Ticks;

                _context.Attachment.Add(attachment);
                _context.SaveChanges();


                var attachmentFinal = _context.Attachment
                                .Include(c => c.Rental.Order.Customer)
                                .Include(m => m.Rental.Machinist)
                                .Include(m => m.Rental.Address)
                                .SingleOrDefault(m => m.Id == attachment.Id);

                SignatureImg.Name = attachmentFinal.Rental.Order.Customer.Name +
                                "-" + attachmentFinal.Rental.Machinist.LastName +
                                "-" + attachment.AttachmentDate.ToString("ddMMyyyy");

                TempData[Constant.Success] = Constant.New;

                // manage email sending to the customer
                // sender configuration + smtp in webconfig file
                try
                {
                    //var receiverEmail = new MailAddress("jimmy.neller@gmail.com", attachmentFinal.Rental.Order.Customer.Name);
                    var sub = "MOREL - Attachement journalier n°" + attachmentFinal.Id +
                        " du " + attachmentFinal.AttachmentDate.ToString("dd/MM/yyyy") +
                        " - Chantier : " + attachmentFinal.Rental.Address.City;
                    var body = "Contenu du mail";
                    var message = new IdentityMessage
                    {
                        Destination = "jimmy.neller@gmail.com",
                        Body = body,
                        Subject = sub
                    };

MachineRental/Views/Attachment/Attachments.cshtml
@using MachineRental.Common
@model IEnumerable<MachineRental.Models.Attachment>

@{
    ViewBag.Title = "Attachements journaliers";
}

<br />
@*<button class="btn pmd-btn-fab pmd-btn-raised pmd-tooltip pmd-ripple-effect btn-primary"
        data-toggle="tooltip" data-placement="right" title="Ajouter une machine"
        type="button" onclick="location.href = '@Url.Action("Create", "Attachments")'">
    <i class="material-icons pmd-md">add</i>
</button>
<br />
<br />*@

<!-- Table Card -->
<div class="pmd-card pmd-z-depth">
    <div class="table-responsive">
        <table id="attachments" class="table pmd-table table-hover table-striped display responsive" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th >@Html.DisplayNameFor(model => model.Id)</th>
                    <th >@Html.DisplayNameFor(model => model.AttachmentDate)</th>
                    <th >@Html.DisplayNameFor(model => model.Rental.MachinistId)</th>
                    <th >@Html.ShortNameFor(model => model.First().Rental.AddressId)</th>
                    <th >@Html.DisplayNameFor(model => model.WorkingHoursTicks)</th>
                    <th >Modifier / Supprimer</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var attachment in Model)
                {
                    <!-- Simple list -->
                    <div tabindex="-1" class="modal fade" id="simple-listing-dialog-@attachment.Id" style="display: none;" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header pmd-modal-bordered">
                                    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                                    <h2 class="pmd-card-title-text">Détails de la machine</h2>
                                </div>
                                <div class="pmd-modal-list">
                                    <dl class="dl-horizontal">
                                        <dt>@Html.DisplayNameFor(model => model.AttachmentDate)</dt>
                                        <dd>@attachment.AttachmentDate.ToString("F")</dd>
                                        <dt>@Html.DisplayNameFor(model => model.Rental.Order.Customer.Name)</dt>
                                        <dd>@Html.DisplayFor(m => attachment.Rental.Order.Customer.Name)</dd>
                                        <dt>@Html.DisplayNameFor(model => model.Rental.Address)</dt>
                                        <dd>@Html.DisplayFor(m => attachment.Rental.Address.Address1)</dd>
                                        <dd>@Html.DisplayFor(m => attachment.Rental.Address.Address2)</dd>
                                        <dd>@Html.DisplayFor(m => attachment.Rental.Address.ZipCode)</dd>
                                        <dd>@Html.DisplayFor(m => attachment.Rental.Address.City)</dd>
                                        <dd>@Html.DisplayFor(m => attachment.Rental.Address.Country)</dd>

                                        <dt>@Html.DisplayNameFor(model => model.Rental.Machinist.LastName)</dt>
                                        <dd>@Html.DisplayFor(m => attachment.Rental.Machinist.LastName)</dd>
                                        <dt>@Html.DisplayNameFor(model => model.Rental.Machine.Number)</dt>
                                        <dd>@Html.DisplayFor(m => attachment.Rental.Machine.Number)</dd>
                                        <dt>@Html.DisplayNameFor(model => model.WorkingHoursTicks)</dt>
                                        @{ var workingHours = TimeSpan.FromTicks(attachment.WorkingHoursTicks).ToString(@"hh\hmm");}
                                        <dd>@workingHours</dd>
                                        <dt>@Html.DisplayNameFor(model => model.Remarks)</dt>
                                        <dd>@Html.DisplayFor(m => attachment.Remarks)</dd>

                                        <dt>@Html.ShortNameFor(model => model.First().IsSigned)</dt>
                                        <dd>@Constant.Signed</dd>
                                    </dl>
                                </div>
                            </div>
                        </div>
                    </div>
                    <tr>
                        <td><a data-target="#simple-listing-dialog-@attachment.Id" data-toggle="modal">@attachment.Id</a></td>
                        <td>@attachment.AttachmentDate.ToString("d")</td>
                        <td>@attachment.Rental.Machinist.LastName</td>
                        <td>@attachment.Rental.Address.City</td>
                        <td>@workingHours</td>
                        <td>
                            <button class="btn btn-sm pmd-btn-fab pmd-btn-raised pmd-ripple-effect btn-warning pmd-tooltip" 
                                    data-toggle="tooltip" data-placement="top" title="Modifier attachement"
                                    type="button">
                                <i class="material-icons md-light pmd-sm"
                                   onclick="location.href = '@Url.Action("Edit", "Attachment", new {id = attachment.Id})'">update</i>
                            </button>
                            <button data-machine-id="@attachment.Id" class="btn btn-sm pmd-btn-fab pmd-btn-raised pmd-ripple-effect btn-danger js-delete pmd-tooltip" 
                                    data-toggle="tooltip" data-placement="top" title="Supprimer attachement"
                                    type="button">
                                <i class="material-icons pmd-sm">delete</i>
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


@section scripts
{
    <script>
    $(document).ready(function () {
        // Manage Toastr after form post
        var success = "@TempData[Constant.Success]";
        if (success === "@Constant.New") {
            toastr.success("@Constant.NewAttachmentSaveSuccess");
            success = "";
        }
        else if (success === "@Constant.Update") {
            toastr.success("@Constant.AttachmentUpdateSuccess");
            success = "";
        }


        //Build JQuery Datatable
        var table = $('#attachments').DataTable({
            responsive: {
                details: {
                    type: 'column',
                    target: 'tr'
                }
            },
            order: [0, 'asc'],
            bFilter: true,
            bLengthChange: true,
            pagingType: "simple",
            "paging": true,
            "searching": true,
            "language": {
                "info": " _START_ - _END_ sur _TOTAL_ ",
                "sLengthMenu": "<span class='custom-select-title'>Résultats par page:</span> <span class='custom-select'> _MENU_ </span>",
                "sSearch": "",
                "sSearchPlaceholder": "Rechercher",
                "sInfoEmpty": "Affichage de l'&eacute;l&eacute;ment 0 &agrave; 0 sur 0 &eacute;l&eacute;ment",
                "sInfoFiltered": "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                processing: "Traitement en cours...",
                infoEmpty: "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                loadingRecords: "Chargement en cours...",
                zeroRecords: "Aucun &eacute;l&eacute;ment &agrave; afficher",
                emptyTable: "Aucune donnée disponible dans le tableau",
                aria: {
                    sortAscending: ": activer pour trier la colonne par ordre croissant",
                    sortDescending: ": activer pour trier la colonne par ordre décroissant"
                },
                "paginate": {
                    "sNext": " ",
                    "sPrevious": " "
                }
            },
            dom:
                "<'pmd-card-title'<'data-table-title'><'search-paper pmd-textfield'f>>" +
                "<'custom-select-info'<'custom-select-item'><'custom-select-action'>>" +
                "<'row'<'col-sm-12'tr>>" +
                "<'pmd-card-footer' <'pmd-datatable-pagination' l i p>>"
        });

        // set datatables options
        $('.custom-select-info').hide();
        $("div.data-table-title").html('<h2 class="pmd-card-title-text">Liste des attachements journaliers</h2>');

        // set column search
        $('#attachments thead tr').clone(true).appendTo( '#attachments thead' );
        $('#attachments thead tr:eq(1) th').each( function (i) {
            var title = $(this).text();
            $(this).html( '<input type="search" class="form-control input-sm" placeholder="'+title+'" />' );

            $( 'input', this ).on( 'keyup change', function () {
                if ( table.column(i).search() !== this.value ) {
                    table
                        .column(i)
                        .search( this.value )
                        .draw();
                }
            } );
        } );

        // activate tooltip management
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });

        // Manage row/data deletion on click on corresponding button
        $("#attachments").on("click", ".js-delete", function () {
            var button = $(this);
            // custom confirm box
            bootbox.confirm({
                message: "Êtes-vous sûr(e) de vouloir supprimer cette machine ?",
                buttons: {
                    cancel: {
                        label: 'Annuler',
                        className: 'btn btn-default pmd-ripple-effect pmd-btn-raised',
                    },
                    confirm: {
                        label: 'Confirmer',
                        className: 'btn btn-primary pmd-ripple-effect pmd-btn-raised',
                    }
                },
                callback: function(result) {
                    if (result) {
                        $.ajax({
                            url: '@Url.Action("Delete", "Attachment")/' + button.attr("data-machine-id"),
                            method: "post",
                            success: function () {
                                toastr.success("Attachement journalier supprimée avec succès");
                                table.row(button.parents("tr")).remove().draw();  // remove element from datatable and not just from the DOM using button.parents("tr").remove()
                            }
                        });
                    }
                }
            });

        });
    });
    </script>
}